name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Build PDF files
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            course_programm.tex
            tickets_main.tex
          latexmk_shell_escape: true
          extra_system_packages: gnuplot

      - name: Gather build artifacts
        if: always()
        run: |
          mkdir -p build build/logs
          mv *.pdf ./build/ || true
          find . -name "*.log" -exec mv '{}' "./build/logs/" ";";

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Contents
          path: build/
          retention-days: 90
          if-no-files-found: error
